### PR TITLE
WIP: docusaurus

### PR DESCRIPTION
**Pull request by strdr4605**
Probably better to create a `docusaurus` branch in the main repo as there will be more PRs before final release.

Check https://v2.docusaurus.io/docs/introduction for docusaurus-v2 guide.

To run docs:

```bash
cd docusaurus
yarn install
yarn start
```

I did simple customization and created `motivation` page for a sample. But `diff` highlighting does not work at the moment and I asked for help in the docusaurus discord channel.

Any ideas about the site theming and docs sections?!

### CODE REVIEW

**Comment by klis87** [comment]
@strdr4605 Thx! I think in theory we could just push it to master, as those are only docs which will be just there anyway not breaking anything

Regarding diff I hope they will solve it, I really care to display it like that as it probably works on imagination how much lines of code this library can save.

Speaking about theming, I think we can use defaults for now and focus on content.

I think I would like to have sections like in main readme, but with subsections and with more detailed examples. We will have dedicated pages to use too so I would also like to have more things, like how to create custom driver, some `Guides` chapter how to solve different problems, maybe how to use with different libraries etc.

But for now the 1st step is to just organize content like in README.md, so `actions`, `reducers`, `middleware` etc

Anyway, I really appreciate your help!

**Comment by strdr4605** [comment]
@klis87 see https://strdr4605.github.io/redux-saga-requests/ 

One thing that I understood making this **Getting started** section is that is way to much text to read

**Comment by klis87** [comment]
@strdr4605 Nice, looking great! I can see you managed to highlight diff!

> Way too many features for first-time users. Should separate in Beginner guide/Advanced guide

Definitely agree, and it should be only about features, not implementation details like function names.

I imagine home page as short list of killer features, also I would really like to have this diff because for many people this tells more that 1000 words. Also I would like to have an image as short movie which shows cool things in action, like spinners everywhere, error handling next to buttons, optimistic updates, caching, network tab opened to see aborts. I will do this once I finish real world example.

Also I think tutorial should be divided into many pages as real case tutorial (like simple books manager application), and long explanation https://strdr4605.github.io/redux-saga-requests/docs/getting-started/usage just paired with proper steps.

We will get there though, for now I am focusing on removing sagas, actually I finished more or less as prototype, but need to add tests. remove legacy code, update examples docs and so on, so it will take some time.

**Comment by klis87** [comment]
Thx again, I merged it and will take a look at the structure, I have some stuff to do first but writing docs should be one of the things I will do in the near future.

**Pull request merged**
